# Generated by Django 5.1.15 on 2026-03-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='single_active_tournament_edition')],
            },
        ),
        migrations.CreateModel(
            name='RuleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('summary', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_sections', to='tournament.tournamentedition')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phase_type', models.CharField(choices=[('qualifiers', 'Clasificatoria'), ('groups', 'Grupos'), ('round_of_16', 'Octavos'), ('quarterfinal', 'Cuartos'), ('semifinal', 'Semifinal'), ('final', 'Final'), ('custom', 'Personalizada')], default='custom', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_public', models.BooleanField(default=False)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Permite guardar formato, cantidad de clasificados u otras reglas variables.')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='tournament.tournamentedition')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('edition', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arena', models.CharField(blank=True, max_length=80)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('score_a', models.PositiveSmallIntegerField(default=0)),
                ('score_b', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('ready', 'Listo'), ('in_progress', 'En juego'), ('finished', 'Finalizado'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos flexibles: tiempo, juez, observaciones, globos explotados, etc.')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_a', to='participants.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_b', to='participants.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_matches', to='participants.team')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournamentphase')),
            ],
            options={
                'ordering': ['scheduled_at', 'created_at'],
                'indexes': [models.Index(fields=['status'], name='tournament__status_9ffd85_idx'), models.Index(fields=['scheduled_at'], name='tournament__schedul_5f9c1b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('team_a', models.F('team_b')), _negated=True), name='prevent_self_match')],
            },
        ),
    ]
