# Generated by Django 5.1.15 on 2026-04-11 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_schoolregistration_unique_school_robot_registration_and_more'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.CharField(choices=[('school', 'Colegios'), ('university', 'Universidades')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Listo'), ('in_progress', 'En progreso'), ('completed', 'Completado')], default='draft', max_length=20)),
                ('shuffle_seed', models.PositiveIntegerField(default=1)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='tournament.tournamentedition')),
            ],
            options={
                'ordering': ['division', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('groups', 'Grupos'), ('purgatory_1', 'Purgatorio 1'), ('round_of_16', 'Octavos'), ('purgatory_2', 'Purgatorio 2'), ('quarterfinal', 'Cuartos'), ('semifinal', 'Semifinal'), ('third_place', 'Tercer lugar'), ('final', 'Final')], max_length=20)),
                ('format_type', models.CharField(choices=[('group', 'Grupo'), ('battle_royale', 'Campal'), ('duel', '1 vs 1'), ('triangular', 'Triangular')], default='duel', max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('ready', 'Listo'), ('in_progress', 'En juego'), ('finished', 'Finalizado'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('arena', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_wins', to='participants.team')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='tournament.divisioncompetition')),
            ],
            options={
                'ordering': ['stage', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DivisionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=4)),
                ('order', models.PositiveSmallIntegerField()),
                ('expected_size', models.PositiveSmallIntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournament.divisioncompetition')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='DivisionGroupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_order', models.PositiveSmallIntegerField()),
                ('final_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournament.divisiongroup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_entries', to='participants.team')),
            ],
            options={
                'ordering': ['slot_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionBattleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_order', models.PositiveSmallIntegerField()),
                ('origin_label', models.CharField(blank=True, max_length=120)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournament.competitionbattle')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battle_entries', to='participants.team')),
            ],
            options={
                'ordering': ['slot_order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('battle', 'team'), name='unique_team_per_battle'), models.UniqueConstraint(fields=('battle', 'slot_order'), name='unique_slot_per_battle')],
            },
        ),
        migrations.AddConstraint(
            model_name='divisioncompetition',
            constraint=models.UniqueConstraint(fields=('edition', 'division'), name='unique_competition_per_division'),
        ),
        migrations.AddConstraint(
            model_name='competitionbattle',
            constraint=models.UniqueConstraint(fields=('competition', 'stage', 'order'), name='unique_battle_order_per_stage'),
        ),
        migrations.AddConstraint(
            model_name='divisiongroup',
            constraint=models.UniqueConstraint(fields=('competition', 'label'), name='unique_group_label_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='divisiongroup',
            constraint=models.UniqueConstraint(fields=('competition', 'order'), name='unique_group_order_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='divisiongroupentry',
            constraint=models.UniqueConstraint(fields=('group', 'team'), name='unique_team_per_group'),
        ),
        migrations.AddConstraint(
            model_name='divisiongroupentry',
            constraint=models.UniqueConstraint(fields=('group', 'slot_order'), name='unique_slot_per_group'),
        ),
        migrations.AddConstraint(
            model_name='divisiongroupentry',
            constraint=models.UniqueConstraint(condition=models.Q(('final_rank__isnull', False)), fields=('group', 'final_rank'), name='unique_rank_per_group'),
        ),
    ]
