# Generated by Django 5.1.15 on 2026-04-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_divisioncompetition_competitionbattle_divisiongroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisioncompetition',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='divisioncompetition',
            name='format_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='competitionbattle',
            name='stage',
            field=models.CharField(choices=[('groups', 'Grupos'), ('purgatory_1', 'Purgatorio 1'), ('round_of_32', 'Ronda de 32'), ('round_of_16', 'Octavos'), ('purgatory_2', 'Purgatorio 2'), ('quarterfinal', 'Cuartos'), ('semifinal', 'Semifinal'), ('third_place', 'Tercer lugar'), ('final', 'Final')], max_length=20),
        ),
    ]
