# Generated by Django 5.1.15 on 2026-05-05 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0007_registration_attendance_workflow'),
        ('tournament', '0004_divisiongroupentry_qualified_from_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('auto_sync', 'Sincronizacion automatica'), ('group_result', 'Resultado de grupos'), ('battle_result', 'Resultado de batalla'), ('manual_move', 'Movimiento manual'), ('status_change', 'Cambio de estado'), ('reintegrated', 'Reintegrado')], max_length=20)),
                ('stage', models.CharField(blank=True, choices=[('groups', 'Grupos'), ('purgatory_1', 'Purgatorio 1'), ('round_of_32', 'Ronda de 32'), ('round_of_16', 'Octavos'), ('purgatory_2', 'Purgatorio 2'), ('quarterfinal', 'Cuartos'), ('semifinal', 'Semifinal'), ('third_place', 'Tercer lugar'), ('final', 'Final')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('active', 'Activo'), ('eliminated', 'Eliminado'), ('repechage', 'En repechaje'), ('qualified', 'Clasificado'), ('withdrawn', 'Retirado')], max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('previous_stage', models.CharField(blank=True, choices=[('groups', 'Grupos'), ('purgatory_1', 'Purgatorio 1'), ('round_of_32', 'Ronda de 32'), ('round_of_16', 'Octavos'), ('purgatory_2', 'Purgatorio 2'), ('quarterfinal', 'Cuartos'), ('semifinal', 'Semifinal'), ('third_place', 'Tercer lugar'), ('final', 'Final')], max_length=20)),
                ('new_stage', models.CharField(blank=True, choices=[('groups', 'Grupos'), ('purgatory_1', 'Purgatorio 1'), ('round_of_32', 'Ronda de 32'), ('round_of_16', 'Octavos'), ('purgatory_2', 'Purgatorio 2'), ('quarterfinal', 'Cuartos'), ('semifinal', 'Semifinal'), ('third_place', 'Tercer lugar'), ('final', 'Final')], max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('active', 'Activo'), ('eliminated', 'Eliminado'), ('repechage', 'En repechaje'), ('qualified', 'Clasificado'), ('withdrawn', 'Retirado')], max_length=20)),
                ('new_status', models.CharField(blank=True, choices=[('active', 'Activo'), ('eliminated', 'Eliminado'), ('repechage', 'En repechaje'), ('qualified', 'Clasificado'), ('withdrawn', 'Retirado')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='tournament.competitionbattle')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='tournament.divisioncompetition')),
                ('new_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_new_entries', to='tournament.divisiongroup')),
                ('previous_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_previous_entries', to='tournament.divisiongroup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_history', to='participants.team')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeamCompetitionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stage', models.CharField(choices=[('groups', 'Grupos'), ('purgatory_1', 'Purgatorio 1'), ('round_of_32', 'Ronda de 32'), ('round_of_16', 'Octavos'), ('purgatory_2', 'Purgatorio 2'), ('quarterfinal', 'Cuartos'), ('semifinal', 'Semifinal'), ('third_place', 'Tercer lugar'), ('final', 'Final')], default='groups', max_length=20)),
                ('current_status', models.CharField(choices=[('active', 'Activo'), ('eliminated', 'Eliminado'), ('repechage', 'En repechaje'), ('qualified', 'Clasificado'), ('withdrawn', 'Retirado')], default='active', max_length=20)),
                ('manual_status_override', models.CharField(blank=True, choices=[('active', 'Activo'), ('eliminated', 'Eliminado'), ('repechage', 'En repechaje'), ('qualified', 'Clasificado'), ('withdrawn', 'Retirado')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_states', to='tournament.divisioncompetition')),
                ('current_battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_states', to='tournament.competitionbattle')),
                ('current_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_states', to='tournament.divisiongroup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_states', to='participants.team')),
            ],
            options={
                'ordering': ['competition', 'team__robot_name'],
                'constraints': [models.UniqueConstraint(fields=('competition', 'team'), name='unique_state_per_team_competition')],
            },
        ),
    ]
