# Generated by Django 5.1.15 on 2026-03-29 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, unique=True)),
                ('institution_type', models.CharField(choices=[('school', 'Colegio'), ('university', 'Universidad')], max_length=20)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category_label', models.CharField(help_text='Categoria operativa visible para el torneo. Ej: Junior, Senior, Universitaria.', max_length=120)),
                ('robot_name', models.CharField(max_length=120)),
                ('robot_weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('coach_name', models.CharField(max_length=120)),
                ('coach_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('coach_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\\\-\\\\s]{7,20}$', 'Ingresa un telefono valido.')])),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='submitted', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('document_number', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('age', models.PositiveSmallIntegerField()),
                ('role', models.CharField(help_text='Ej: conductor, programador, diseno, soporte.', max_length=80)),
                ('is_team_lead', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
