# Generated by Django 5.1.15 on 2026-03-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='tournament.tournamentedition'),
        ),
        migrations.AddField(
            model_name='team',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='participants.institution'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='participants.team'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['edition', 'status'], name='participant_edition_02c3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['status'], name='participant_status_6dc93b_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['institution', 'category_label'], name='participant_institu_5785e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('edition', 'institution', 'name'), name='unique_team_per_edition'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['document_number'], name='participant_documen_45878b_idx'),
        ),
    ]
