# Generated by Django 5.1.15 on 2026-03-29 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_initial'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(max_length=180)),
                ('institution_city', models.CharField(blank=True, max_length=120)),
                ('institution_department', models.CharField(blank=True, max_length=120)),
                ('institution_contact_email', models.EmailField(blank=True, max_length=254)),
                ('institution_contact_phone', models.CharField(blank=True, max_length=30)),
                ('team_name', models.CharField(max_length=120)),
                ('category_label', models.CharField(blank=True, max_length=120)),
                ('robot_name', models.CharField(max_length=120)),
                ('robot_weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('coach_name', models.CharField(max_length=120)),
                ('coach_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('coach_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]{7,20}$', 'Ingresa un telefono valido.')])),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='submitted', max_length=20)),
                ('school_level', models.CharField(blank=True, help_text='Ej: primaria, bachillerato, media tecnica o categoria escolar definida por el torneo.', max_length=120)),
                ('principal_teacher', models.CharField(blank=True, help_text='Nombre del docente o responsable institucional.', max_length=120)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tournament.tournamentedition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('document_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('is_team_lead', models.BooleanField(default=False)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='participants.schoolregistration')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='UniversityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(max_length=180)),
                ('institution_city', models.CharField(blank=True, max_length=120)),
                ('institution_department', models.CharField(blank=True, max_length=120)),
                ('institution_contact_email', models.EmailField(blank=True, max_length=254)),
                ('institution_contact_phone', models.CharField(blank=True, max_length=30)),
                ('team_name', models.CharField(max_length=120)),
                ('category_label', models.CharField(blank=True, max_length=120)),
                ('robot_name', models.CharField(max_length=120)),
                ('robot_weight_grams', models.PositiveIntegerField(blank=True, null=True)),
                ('coach_name', models.CharField(max_length=120)),
                ('coach_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('coach_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s]{7,20}$', 'Ingresa un telefono valido.')])),
                ('emergency_contact', models.CharField(blank=True, max_length=120)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='submitted', max_length=20)),
                ('academic_program', models.CharField(blank=True, help_text='Programa academico principal del equipo.', max_length=160)),
                ('faculty', models.CharField(blank=True, help_text='Facultad, escuela o departamento al que pertenece el equipo.', max_length=160)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tournament.tournamentedition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('document_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('is_team_lead', models.BooleanField(default=False)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='participants.universityregistration')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='schoolregistration',
            index=models.Index(fields=['edition', 'status'], name='participant_edition_129699_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolregistration',
            index=models.Index(fields=['institution_name'], name='participant_institu_4fdbd6_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolparticipant',
            index=models.Index(fields=['document_number'], name='participant_documen_53c3db_idx'),
        ),
        migrations.AddIndex(
            model_name='universityregistration',
            index=models.Index(fields=['edition', 'status'], name='participant_edition_c19594_idx'),
        ),
        migrations.AddIndex(
            model_name='universityregistration',
            index=models.Index(fields=['institution_name'], name='participant_institu_35f822_idx'),
        ),
        migrations.AddIndex(
            model_name='universityparticipant',
            index=models.Index(fields=['document_number'], name='participant_documen_ea7ecf_idx'),
        ),
    ]
