from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0003_schoolregistration_schoolparticipant_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schoolregistration",
            old_name="coach_name",
            new_name="responsible_name",
        ),
        migrations.RenameField(
            model_name="schoolregistration",
            old_name="coach_phone",
            new_name="contact_phone",
        ),
        migrations.RenameField(
            model_name="schoolregistration",
            old_name="coach_email",
            new_name="contact_email",
        ),
        migrations.RemoveField(
            model_name="schoolregistration",
            name="institution_city",
        ),
        migrations.RemoveField(
            model_name="schoolregistration",
            name="institution_department",
        ),
        migrations.RemoveField(
            model_name="schoolregistration",
            name="institution_contact_email",
        ),
        migrations.RemoveField(
            model_name="schoolregistration",
            name="institution_contact_phone",
        ),
        migrations.RemoveField(
            model_name="schoolregistration",
            name="team_name",
        ),
        migrations.RemoveField(
            model_name="schoolregistration",
            name="category_label",
        ),
        migrations.RemoveField(
            model_name="schoolregistration",
            name="robot_weight_grams",
        ),
        migrations.RemoveField(
            model_name="schoolregistration",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="schoolregistration",
            name="emergency_phone",
        ),
        migrations.RemoveField(
            model_name="schoolregistration",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="schoolregistration",
            name="school_level",
        ),
        migrations.RemoveField(
            model_name="schoolregistration",
            name="principal_teacher",
        ),
        migrations.RemoveField(
            model_name="schoolparticipant",
            name="email",
        ),
        migrations.RemoveField(
            model_name="schoolparticipant",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="schoolparticipant",
            name="age",
        ),
        migrations.RenameField(
            model_name="universityregistration",
            old_name="coach_name",
            new_name="responsible_name",
        ),
        migrations.RenameField(
            model_name="universityregistration",
            old_name="coach_phone",
            new_name="contact_phone",
        ),
        migrations.RenameField(
            model_name="universityregistration",
            old_name="coach_email",
            new_name="contact_email",
        ),
        migrations.RemoveField(
            model_name="universityregistration",
            name="institution_city",
        ),
        migrations.RemoveField(
            model_name="universityregistration",
            name="institution_department",
        ),
        migrations.RemoveField(
            model_name="universityregistration",
            name="institution_contact_email",
        ),
        migrations.RemoveField(
            model_name="universityregistration",
            name="institution_contact_phone",
        ),
        migrations.RemoveField(
            model_name="universityregistration",
            name="team_name",
        ),
        migrations.RemoveField(
            model_name="universityregistration",
            name="category_label",
        ),
        migrations.RemoveField(
            model_name="universityregistration",
            name="robot_weight_grams",
        ),
        migrations.RemoveField(
            model_name="universityregistration",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="universityregistration",
            name="emergency_phone",
        ),
        migrations.RemoveField(
            model_name="universityregistration",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="universityregistration",
            name="academic_program",
        ),
        migrations.RemoveField(
            model_name="universityregistration",
            name="faculty",
        ),
        migrations.RemoveField(
            model_name="universityparticipant",
            name="email",
        ),
        migrations.RemoveField(
            model_name="universityparticipant",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="universityparticipant",
            name="age",
        ),
    ]
