# Generated by Django 5.1.15 on 2026-03-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_align_registration_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolparticipant',
            name='role',
            field=models.CharField(blank=True, help_text='Ej: lider, integrante 2, integrante 3.', max_length=80),
        ),
        migrations.AlterField(
            model_name='universityparticipant',
            name='role',
            field=models.CharField(blank=True, help_text='Ej: lider, integrante 2, integrante 3.', max_length=80),
        ),
    ]
