# Generated by Django 5.1.15 on 2026-03-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0005_alter_schoolparticipant_role_and_more'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schoolregistration',
            constraint=models.UniqueConstraint(fields=('edition', 'institution_name', 'robot_name'), name='unique_school_robot_registration'),
        ),
        migrations.AddConstraint(
            model_name='universityregistration',
            constraint=models.UniqueConstraint(fields=('edition', 'institution_name', 'robot_name'), name='unique_university_robot_registration'),
        ),
    ]
